# azure-pipelines.yml

trigger:
  branches:
    include:
      - '*'  # Qualquer branch pode disparar o pipeline

# Especifica a pool 'Default' onde o agente self-hosted está registrado
pool:
  name: 'Default'  # Pool onde o seu agente está registrado
  demands:
    - agent.name -equals 'Agenteselfhosted'  # Nome exato do seu agente self-hosted

steps:
  # Checkout do código do repositório GitHub ou Azure DevOps
  - checkout: self

  # Instalar o JDK 11, com suporte para diferentes sistemas operacionais
  - script: |
      if [ "$(uname)" = "Linux" ]; then
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
      elif [ "$(uname)" = "Darwin" ]; then
        brew tap AdoptOpenJDK/openjdk
        brew install --cask adoptopenjdk11
      else
        echo "Instalação manual do JDK necessária para Windows"
      fi
      java -version  # Verifica se o JDK foi instalado corretamente
    displayName: 'Instalar JDK 11'
    condition: succeeded()  # Executa somente se o passo anterior tiver sucesso

  # Build do projeto com Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Certifique-se de que este caminho está correto
      goals: 'clean install'
      options: '-B'  # Evita prompts interativos durante a execução
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  # Publicar cobertura de código usando JaCoCo
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: 'target/site/jacoco/jacoco.xml'
      reportDirectory: 'target/site/jacoco'
      failIfCoverageEmpty: true
