# azure-pipelines.yml

trigger:
  branches:
    include:
      - '*'

# Utilize a pool 'Default' onde o seu agente self-hosted está registrado
pool:
  name: 'Default'

steps:
  # Faz o checkout do código do repositório
  - checkout: self

  # Verifica se o Maven e o JDK estão instalados
  - script: |
      java -version  # Verifica a versão do JDK instalado
      mvn -version   # Verifica se o Maven está instalado corretamente
    displayName: 'Verificar JDK e Maven'

  # Build do projeto com Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Certifique-se de que o arquivo pom.xml está no diretório correto
      goals: 'clean install'
      options: '-B'  # Evita prompts interativos
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  # Publicar cobertura de código usando JaCoCo
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: 'target/site/jacoco/jacoco.xml'
      reportDirectory: 'target/site/jacoco'
      failIfCoverageEmpty: true
