# azure-pipelines.yml

trigger:
  branches:
    include:
      - '*'

pool:
  name: 'Default'  # Pool onde o seu agente está registrado

# Você pode remover demands se não precisar especificar o agente pelo nome.
# demands:
#   - agent.name -equals 'Agenteselfhosted'

steps:
  - checkout: self

  # Instalar JDK 11
  - script: |
      if [ "$(uname)" = "Linux" ]; then
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk maven  # Instalando Maven no Linux também
      elif [ "$(uname)" = "Darwin" ]; then
        brew tap AdoptOpenJDK/openjdk
        brew install --cask adoptopenjdk11
        brew install maven  # Instalando Maven no MacOS
      else
        echo "Instalação manual do Maven necessária para Windows"
      fi
      java -version
      mvn -version  # Verifica se o Maven foi instalado corretamente
    displayName: 'Instalar JDK 11 e Maven'
    condition: succeeded()

  # Build do projeto com Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-B'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  # Publicar cobertura de código usando JaCoCo
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'JaCoCo'
      summaryFileLocation: 'target/site/jacoco/jacoco.xml'
      reportDirectory: 'target/site/jacoco'
      failIfCoverageEmpty: true
