trigger:
  branches:
    include:
      - main  # Dispara o pipeline em cada push na branch main

pool:
  vmImage: 'ubuntu-latest'  # Utiliza uma VM com Ubuntu

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Arquivo de configuração do Maven
    goals: 'clean install'   # Limpa e instala dependências do projeto

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'            # Roda os testes automatizados

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Test Results'  # Publica os resultados dos testes

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'  # Diretório de saída
    artifactName: 'drop'
    publishLocation: 'Pipeline'
